name: 'Terraform CI/CD Pipeline'



on:

  push:

    branches:

      - main



permissions:

  contents: read

  id-token: write # Crucial for Workload Identity Federation exchange



jobs:

  terraform:

    name: 'Terraform Automate'

    runs-on: ubuntu-latest



    steps:

    # Step 1: Check out the code from GitHub to the runner machine

    - name: Checkout Code

      uses: actions/checkout@v4



    # Step 2: Authenticate to GCP using Keyless Workload Identity Federation

    - name: Authenticate to Google Cloud

      uses: google-github-actions/auth@v2

      with:

        workload_identity_provider: 'projects/250794715777/locations/global/workloadIdentityPools/github-pool/providers/github-provider'

        service_account: 'github-actions-sa@project-f2bce33d-23f5-4831-9b4.iam.gserviceaccount.com'



    # Step 3: Install the exact version of Terraform CLI on the runner

    - name: Setup Terraform

      uses: hashicorp/setup-terraform@v3

      with:

        terraform_version: 1.7.0
        terraform_wrapper: false


    # Step 4: Run Terraform Init

    - name: Terraform Init

      run: terraform init

        # Step 5: Run Terraform Plan to preview changes
    - name: Terraform Plan
      env:
        TF_VAR_project_id: 'project-f2bce33d-23f5-4831-9b4'
        TF_VAR_gcp_region: 'us-central1' # Change to your region if different
        TF_VAR_environment_prefix: 'globant-prep'
      run: terraform plan -no-color -input=false

    # Step 6: Run Terraform Apply (Automated with -auto-approve)
    - name: Terraform Apply
      env:
        TF_VAR_project_id: 'project-f2bce33d-23f5-4831-9b4'
        TF_VAR_gcp_region: 'us-central1'
        TF_VAR_environment_prefix: 'globant-prep'
      run: terraform apply -auto-approve -no-color -input=false
